version: "3.3"
services:
  pihole:
    container_name: pihole
    hostname: Pinets-RazoBeckett
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
      - "443:443"
      #- "67:67"  # If you intend to use Pi-hole as DHCP as well, uncomment the port
    environment:
      TZ: $TIMEZONE # set your time zone
      WEBPASSWORD: $PIHOLE_PASSWORD
      PIHOLE_DNS_: "10.11.12.3;10.11.12.4" # Custom upstream DNS servers in our case we are using Unbound and Cloudflared container/service.
    volumes:
      - "~/docker_stuff/pihole/etc/pihole/:/etc/pihole/"
      - "~/docker_stuff/pihole/etc/dnsmasq.d/:/etc/dnsmasq.d/"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    networks:
      pinets:
        ipv4_address: 10.11.12.2 # Assign an IP address within the custom subnet
    restart: unless-stopped

  #--------------------------------------------------------------------

  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    # There's no need to expose these ports; they are simply for your reference to know which ports are used by this service.
    #ports:
    #  - "5353:53/tcp"
    #  - "5353:53/udp"
    volumes:
      - ~/docker_stuff/unbound:/opt/unbound/etc/ubound
    networks:
      pinets:
        ipv4_address: 10.11.12.3 # Assign an IP address within the custom subnet
    restart: unless-stopped

  #--------------------------------------------------------------------

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    networks:
      pinets:
        ipv4_address: 10.11.12.4 # Assign an IP address within the custom subnet
    environment:
        TZ: $TIMEZONE
    volumes:
      - ~/docker_stuff/cloudflared/config:/etc/cloudflared # Map the config directory to the container's /etc/cloudflared directory
    command: ["proxy-dns", "--address", "0.0.0.0", "--upstream", "$UPSTREAM1", "--upstream", "$UPSTREAM2"]
    restart: unless-stopped

  #--------------------------------------------------------------------

networks:
  pinets:
    external: true